services:
  riscv-builder:
    build: .
    container_name: riscv-image-builder
    privileged: true                  # Required for losetup, mount, chroot, binfmt
    volumes:
      - ./input:/input               # Put kernel .deb files and rtthread-n308.elf here
      - ./output:/output             # efi.img, rootfs.ext4 and minbase cache appear here
    environment:
      - IMAGE_SIZE_MB=8192           # rootfs.ext4 size in MB
      - EFI_SIZE_MB=512              # efi.img size in MB
      - MIRROR=http://deb.debian.org/debian
      - HOSTNAME=riscv-debian
      - ROOT_PASSWORD=root           # Change this!
      - USER_NAME=user               # Regular user account
      - USER_PASSWORD=user           # Change this!
      - INSTALL_XFCE=true            # Set to false to skip XFCE
      - TIMEZONE=Europe/Rome         # Set your timezon
